version: '2'
networks:
  fabric-ca:
services:
  51nca:
    container_name: 51nca
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b 51nca:123456 --cfg.affiliations.allowremove --cfg.identities.allowremove --port 7057'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./51nca-server:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca
    ports:
      - 7057:7057