# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.PayBF.pbfchain.com:
services:
  peer0.PayBF.pbfchain.com:
    container_name: peer0.PayBF.pbfchain.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.PayBF.pbfchain.com
    networks:
      default:
        aliases:
          - paybf

  PayBFcli:
    container_name: PayBFcli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - GODEBUG=netdns=go      
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.PayBF.pbfchain.com:7051
      - CORE_PEER_LOCALMSPID=PayBFMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/PayBF.pbfchain.com/peers/peer0.PayBF.pbfchain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/PayBF.pbfchain.com/peers/peer0.PayBF.pbfchain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/PayBF.pbfchain.com/peers/peer0.PayBF.pbfchain.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/PayBF.pbfchain.com/users/Admin@PayBF.pbfchain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      default:
        aliases:
          - paybf
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./ca-client/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.PayBF.pbfchain.com
   
