version: '2'
networks:
  fabric-ca:
services:
  ordersca:
    container_name: ordersca
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b ordersca:123456 --cfg.affiliations.allowremove --cfg.identities.allowremove --port 7055'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./ordersca-server:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca
    ports:
      - 7055:7055