version: '2'
networks:
  fabric-ca:
services:
  PayBFca:
    container_name: PayBFca
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b PayBFca:123456 --cfg.affiliations.allowremove --cfg.identities.allowremove --port 7056'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./PayBFca-server:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-ca
    ports:
      - 7056:7056
      
      
      
      
      
      
      
